<?php
namespace Gemy\MygiftApi;
use Illuminate\Support\ServiceProvider;
class MyGistServiceProvider extends ServiceProvider
{
    public function boot()
    {

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
